version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./static:/code/static
      - ./configs/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: wb01
    command: bash -c "sh scripts/web.sh"
    volumes:
      - .:/code
      - ./static:/code/static
    depends_on:
      - db
  db:
    container_name: db01
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: